### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by winksaville** [cksystemsgroup/scal#12] opened 2015-03-13 18:46 UTC
I tried to compile scal following the instructions in the README.md and it failed, the first and last errors are below and the full error output is here (https://drive.google.com/file/d/0B-KTY7zi7eZHQ3FfWGp1ZzBSekE/view?usp=sharing). I'm guessing the problem is that I'm using gcc 4.9.1, what compilers are you using?

-- Wink

  CXX(target) out/Debug/obj.target/computational-load/src/benchmark/computational-load/computational-load.o
In file included from src/util/allocation.h:21:0,
                 from src/util/malloc-compat.h:18,
                 from src/util/malloc.h:8,
                 from src/util/atomic_value128.h:14,
                 from src/util/atomic_value.h:19,
                 from src/datastructures/distributed_queue_interface.h:8,
                 from src/datastructures/ms_queue.h:18,
                 from src/benchmark/computational-load/computational-load.cc:12:
src/util/platform.h:12:30: error: expected ‘)’ before ‘__attribute__’
 #define always_inline inline __attribute__((always_inline))

and the last errors were:

/usr/include/c++/4.9/atomic: In function ‘void std::atomic_flag_clear_explicit(volatile std::atomic_flag*, std::memory_order)’:
/usr/include/c++/4.9/atomic:786:10: error: ‘volatile struct std::atomic_flag’ has no member named ‘clear’
   { __a->clear(__m); }
          ^
In file included from /usr/include/c++/4.9/atomic:41:0,
                 from src/util/atomic_value_new.h:12,
                 from src/datastructures/pool.h:8,
                 from src/datastructures/queue.h:8,
                 from src/datastructures/ms_queue.h:19,
                 from src/benchmark/computational-load/computational-load.cc:12:
/usr/include/c++/4.9/bits/atomic_base.h: In instantiation of ‘std::__atomic_base<_IntTp>::__int_type std::__atomic_base<_IntTp>::operator=(std::__atomic_base<_IntTp>::__int_type) [with _ITp = bool; std::__atomic_base<_IntTp>::__int_type = bool]’:
/usr/include/c++/4.9/atomic:70:35:   required from here
/usr/include/c++/4.9/bits/atomic_base.h:379:11: error: ‘store’ was not declared in this scope
  store(__i);
           ^
/usr/include/c++/4.9/bits/atomic_base.h: In instantiation of ‘std::__atomic_base<_IntTp>::__int_type std::__atomic_base<_IntTp>::operator=(std::__atomic_base<_IntTp>::__int_type) volatile [with _ITp = bool; std::__atomic_base<_IntTp>::__int_type = bool]’:
/usr/include/c++/4.9/atomic:74:35:   required from here
/usr/include/c++/4.9/bits/atomic_base.h:386:11: error: ‘store’ was not declared in this scope
  store(__i);
           ^
computational-load.target.mk:87: recipe for target 'out/Debug/obj.target/computational-load/src/benchmark/computational-load/computational-load.o' failed
make: *** [out/Debug/obj.target/computational-load/src/benchmark/computational-load/computational-load.o] Error 1

**Comment by mlippautz** [comment] 2015-03-14 14:08
Should be fixed in 4e1e7158263ce7fcf192bbeedf62c999390070e2. The issue was caused by a name clash between our code and glibc additions in 4.9.

We generally use the latest Ubuntu LTS (currently 14.04) as our environment for Scal. Currently this means we check building everything using gcc-4.8 and friends.

If you have any further troubles just reopen the issue or drop us a mail.

-Michael

**Closed by mlippautz** 2015-03-14 14:08 UTC
